name: fire_todo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.11.1

dependencies:
  about: ^2.2.0
  another_flushbar: ^2.2.4
  bloc: ^9.2.1
  dart_either: ^2.2.0
  device_meta: ^3.0.1
  dio: ^5.11.0
  equatable: ^2.1.0

  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1
  flutter_exit_app: ^2.1.2
  flutter_launcher_icons: ^0.14.4
  flutter_modular: ^7.1.0
  flutter_native_splash: ^2.4.8
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.3.0
  flutter_terms_viewer: ^1.0.2
  freezed_annotation: any
  gap: ^3.0.1
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  intl: ^0.20.3
  json_annotation: any
  loader_overlay: ^5.0.0
  logger: ^2.7.0
  package_info_plus: ^10.2.1
  path_provider: ^2.1.6
  pretty_dio_logger: ^1.4.0
  rename: ^3.1.0
  shared_preferences: ^2.5.5
  syncfusion_flutter_core: ^34.2.5
  syncfusion_flutter_datepicker: ^34.2.5

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.13.1
  flutter_gen_runner: ^5.15.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  hive_ce_generator: ^1.11.1
  hive_ce_test: ^2.0.0
  integration_test:
    sdk: flutter
  json_serializable: any
  mocktail: ^1.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/md/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
